ang/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ang import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name='home'),
    url(r'^besede/', include('besede.urls', namespace='besede')),
] 

besede/urls.py
from django.conf.urls import url

from besede import views

urlpatterns = [
    url(r'vpisN/$', views.vpisN, name='vpisN'),
    url(r'vpisS/$', views.vpisS, name='vpisS'),
    url(r'vpisB/$', views.vpisB, name='vpisB'),    
    url(r'kviz/$',   views.kviz,  name='kviz' ),
    url(r'kvizB/$',  views.kvizB,  name='kvizB' ),
    url(r'kvizC/$',  views.kvizC,  name='kvizC' ),
]

besede/models.py
from django.db import models

# Create your models here.

class Nivo(models.Model):  
  ime_nivoja = models.CharField(max_length=100, default='Nivo')

  def __str__(self):
    return self.ime_nivoja.encode('utf8')



class Sklop(models.Model):
  nivo       = models.ForeignKey(Nivo)
  ime_sklopa = models.CharField(max_length=50)

  def __str__(self):
    return self.ime_sklopa.encode('utf8') 
  
  

class Beseda(models.Model):
  sklop     = models.ForeignKey(Sklop)
  beseda    = models.CharField(max_length=100)
  prevod    = models.CharField(max_length=100)
  opis      = models.CharField(max_length=100, default="")

  def __str__(self):
    return self.beseda.encode('utf8') + " = " + \
           self.prevod.encode('utf8') + " (" + \
           self.opis  .encode('utf8') + ")"
  

besede/forms.py
from django import forms

class NivoForm(forms.Form):
    nID    = forms.IntegerField(label='nID')
    nivo   = forms.CharField(label='Nivo',   max_length=100)
    akcija = forms.CharField(label='Akcija', max_length=100)

class SklopForm(forms.Form):
    nID    = forms.IntegerField(label='nID')
    sID    = forms.IntegerField(label='sID')
    sklop  = forms.CharField(label='Sklop',  max_length=100)
    akcija = forms.CharField(label='Akcija', max_length=100)

class BesedaForm(forms.Form):
    sID    = forms.IntegerField(label='sID')
    bID    = forms.IntegerField(label='bID')
    beseda = forms.CharField(label='Beseda',  max_length=100)
    prevod = forms.CharField(label='Prevod',  max_length=100)
    opis   = forms.CharField(label='Opis',    max_length=100)
    akcija = forms.CharField(label='Akcija',  max_length=100)

ang/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register

from besede.models import Nivo

# @login_required
def home(request):
	
	return render_to_response(
        'angindex.html',
        {
          'title'  : "ANGlescina",
        }
        , context_instance=RequestContext(request)
    )

besede/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register
from django.shortcuts import render
import random

from besede.models import Nivo
from besede.models import Sklop
from besede.models import Beseda
from besede.forms import NivoForm
from besede.forms import SklopForm
from besede.forms import BesedaForm

def napaka(request, msg):
	return render(request, 'napaka.html', 
    	{
    	  'napaka'    : msg,
        }
    )

# @login_required
def vpisN(request):
	# ce je bila metoda klicana preko forme (nov vpis),
	# nov nivo vpisem v bazo
	if request.method == 'POST':        
		nivo = NivoForm(request.POST)
		try:
   		  if nivo.is_valid():
			nID        = nivo.cleaned_data['nID']
			akcija     = nivo.cleaned_data['akcija']
			imeNivoja  = nivo.cleaned_data['nivo']
			if akcija == "ADD":
				n = Nivo(ime_nivoja = imeNivoja)
				n.save()
			elif akcija == "DEL":
				Nivo.objects.filter(id=nID).delete()
		except:
			return napaka(request, "Napaka pri definiciji nivoja")
        	

	# nato preberem vse nivoje in jih izpisem
	nivoji = list(Nivo.objects.all())

	return render(request, 'vpisN.html', 
    	{
          'nivoji'  : nivoji,
        }
    )

# @login_required
def vpisS(request):
	nID = 0
	if request.method == 'POST':        
		sklop = SklopForm(request.POST)
		if sklop.is_valid():
			nID       = sklop.cleaned_data['nID']
			sID       = sklop.cleaned_data['sID']
			imeSklopa = sklop.cleaned_data['sklop']
			akcija    = sklop.cleaned_data['akcija']
			if akcija == "ADD":
				parentNivo = Nivo.objects.get(id=nID)
				s = Sklop(ime_sklopa=imeSklopa, nivo=parentNivo)
				s.save()
			elif akcija == "DEL":
				Sklop.objects.filter(id=sID).delete()
		else:
			return napaka(request, "Vpisi ime sklopa!")
	else:
		nID = request.GET.get('nID', 0)

	try:
	  parentNivo = Nivo.objects.get(id=nID)
	  sklopi = list(Sklop.objects.filter(nivo=parentNivo))	
	except:
	  return napaka(request, "Neznan sklop!")
	return render(request, 'vpisS.html', 
    	{
    	  'nID'       : nID,
    	  'imeNivoja' : parentNivo.ime_nivoja,
          'sklopi'    : sklopi,
        }
    )

# @login_required
def vpisB(request):
	sID = 0
	if request.method == 'POST':        
		beseda = BesedaForm(request.POST)
		try:
		  if beseda.is_valid():
			sID       = beseda.cleaned_data['sID']
			bID       = beseda.cleaned_data['bID']
			iBeseda   = beseda.cleaned_data['beseda']
			iPrevod   = beseda.cleaned_data['prevod']
			iOpis     = beseda.cleaned_data['opis']
			akcija    = beseda.cleaned_data['akcija']			
			if akcija == "ADD":
				parentSklop = Sklop.objects.get(id=sID)

				b = Beseda(
					  sklop  = parentSklop, beseda = iBeseda,
					  prevod = iPrevod,     opis   = iOpis
					)
				b.save()
			elif akcija == "DEL":
				Beseda.objects.filter(id=bID).delete()
		except:
			return napaka(request, "Narobe definirana beseda")
	else:
		sID = request.GET.get('sID', 0)

	try:
	  parentSklop = Sklop.objects.get(id=sID)
  	  besede = list(Beseda.objects.filter(sklop=parentSklop))
  	  imeSklopa = parentSklop.ime_sklopa
  	  imeNivoja = parentSklop.nivo.ime_nivoja	
	except:
		return napaka(request, "Vpisi besedo in prevod")	    

	return render(request, 'vpisB.html', 
    	{
    	  'sID' : sID,
    	  'nID' : parentSklop.nivo.id,
    	  'imeSklopa' : imeSklopa,
    	  'imeNivoja' : imeNivoja,
    	  'besede'    : besede
        }
    )


# @login_required
def kviz(request):
	nivoji = list(Nivo.objects.all())

	return render(request, 'kvizA.html', 
    	{
           'nivoji'  : nivoji,
        }
    )

# @login_required
def kvizB(request):
	try:
	  nID        = request.GET.get('nID', 0)	
	  parentNivo = Nivo.objects.get(id=nID)
	  sklopi     = list(Sklop.objects.filter(nivo=parentNivo))	
	except:
	  return napaka(request, "Neznan nivo!")

	return render(request, 'kvizB.html', 
    	{
    	   'nivo'    : parentNivo,
    	   'nID'     : nID,
           'sklopi'  : sklopi,
        }
    )

# @login_required
def kvizC(request):
	try:
	  nID        = request.GET.get('nID', 0)	
	  qNo        = request.GET.get('qNo', 0)
	  sklops     = request.GET.get('sklops', 0)

	  if (sklops == "/"):
	  	sklopi = []
	  else:
	  	sklopi     = map(int, sklops.split(":"));

	  besede     = list(Beseda.objects.all())
  	  besede     = [x for x in besede if (x.sklop.id in sklopi)]

  	  qNo = min(int(qNo), len(besede))


  	  selBes = random.sample(besede, qNo)

	except :
	  return napaka(request, "Napaka - " + e)

	return render(request, 'kvizC.html', 
    	{
    	   'nID'     : nID,
           'qNo'     : qNo,
           'sklopi'  : sklopi,
           'besede'  : selBes,
        }
    )

ang/templates/angindex.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}
<div class="ozadje sredina">
  <font size=+15 color="FF0000">BESEdišče</font>
</div>
{% endblock %}

ang/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="utf-8" />
    <title>BESEDišče</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Font awesome include -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- jQuery include -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap include -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Main style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link href="{% static 'css/moj.css' %}" rel="stylesheet">

</head>

<body>
    <div class="container-fluid">
        {% include 'menu.html' %}
    </div>
    <div class="container-fluid main">
        {% block body_block %}{% endblock %}
    </div>
</body>

ang/templates/menu.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >
        <img alt="BESEDišče" src="...">
      </a>
    </div>
    <ul class="nav navbar-nav">
        <li ><a href="/">Domov</a></li>
        <li><a href="/besede/vpisN">Pregled in vnos besed</a></li>
        <li><a href="/besede/kviz">KVIZ</a></li>
    </ul>
  </div>
</nav>

besede/templates/kvizA.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<div class="ozadje">
<center>
<h1 class="bottom-ena"><br>KVIZ<br>Izberi področje</h1>
<table width = 200>
   {% for nivo in nivoji %}
     <tr><td>
      <a href="{% url 'besede:kvizB'%}?nID={{ nivo.id }}">
        {{ nivo }}</a><br>
     </td></tr>       
   {%endfor %}
</table>
</center>  
</div>
{% endblock %}

besede/templates/kvizB.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<div class="container ozadje">
<center><h1 class="bottom-ena"><br>{{ nivo }}</h1></center>
<hr>


  <div class="col-md-4" style="align:left;">
    <p><input type="checkbox" onClick="preklop(this)" value="x"/> 
      -- IZBERI VSE --
    </p>
  
    {% for sklop in sklopi %}
      <p><input type="checkbox" name="cb" 
   	            value="{{ sklop.id }}">&nbsp; {{ sklop }}
      </p>
    {%endfor %}
  </div>

  <div class="col-md-4">
    Število vprašanj:&nbsp;&nbsp;
    <input type="input" id="qnumber" value="20" />
   	            
  </div>	

  <div class="col-md-4">
    <input type="submit" name="go" value="Sestavi kviz!" 
           data-toggle="modal"   data-target="#myModal"
           onclick="return on_kviz()"
    />
  </div>

</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <center><h4 class="modal-title">{{ nivo }} - kviz</h4></center>
      </div>
      <div class="modal-body">
        <div id=kviz>
          ...
        </div>      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="container ozadje">
<hr>
</div>

<script>
  $(".gumb").hover(function () {
    $(this).css({
        'cursor': 'pointer'
    });
  });

  function preklop(source) {
    $(':checkbox').each(function() {
            this.checked = source.checked;                        
    });
  }

  function on_kviz() {
    var ids="";
    $(":checkbox").each(function() {
      var vval = $(this).val();
      if ($(this).is(":checked") && vval != "x") {
        if (ids != "") ids = ids + ":";
        ids += vval;
      }
    });
    if (ids == "") ids="/";
        
    var params = "?nID={{ nID }}&qNo=" + 
         document.getElementById('qnumber').value;
    params    += "&sklops=" + ids;

    $("#kviz").load("{% url 'besede:kvizC'%}" + params);
  }

</script>


{% endblock %}

besede/templates/kvizC.html
<table>
{% for b in besede %}
<tr height=40><td>
  <span onclick="toggle_visibility('{{ b.beseda }}');">{{ b.beseda }}</span> &nbsp;&nbsp;&nbsp;
</td>
<td>
  <input id="edValue" type="text"
    onKeyUp="edValueKeyPress(this,'{{ b.beseda }}','{{ b.prevod }}')" >
</td>
<td valign=center style="display:none;" id="{{ b.beseda }}"> {{ b.prevod }}
</td>
</tr>
{%endfor %}
</table>

<script>
function edValueKeyPress(iField, beseda, prevod) {
	var trBeseda = iField.value;
	// $("#"+beseda).text(iField.value);
	if (trBeseda == "") {
	  iField.style.backgroundColor = "";
	} else if (trBeseda.toUpperCase() == prevod.toUpperCase()) {
      iField.style.backgroundColor = "#99FFBB";
    } else {
      iField.style.backgroundColor = "#FF6699";
    }
}

function toggle_visibility(id) {
  var e = document.getElementById(id);
  if(e.style.display == 'block')
    e.style.display = 'none';
  else
    e.style.display = 'block';
}
</script>

besede/templates/napaka.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<script >

</script>

<div class="ozadje">
	<h2>Napaka: {{ napaka }}</h2>
</div>
{% endblock %}

besede/templates/vpisB.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<script >

</script>

<div class="ozadje">
<center>
  <h1>&nbsp;<br><a href="{% url 'besede:vpisS'%}?nID={{ nID }}">{{ imeNivoja }}</a></h1>
  <h2 class="bottom-dva">{{ imeSklopa }}</h2>
</center>

<div class="row">
<div class="col-md-1"></div>
<div class="col-md-10">
      <form action="{% url 'besede:vpisB'%}" method="POST" class="form-horizontal">
        {% csrf_token %}
        <input type="hidden" name="akcija"    value="ADD">
        <input type="hidden" name="sID"       value="{{ sID }}">
        <input type="hidden" name="bID"       value="0">
        <div class="row">
            <div class="form-group col-xs-2" style="valign:right;">
              &nbsp;<br>
            </div>
            <div class="form-group col-xs-2">
              Beseda<br>
              <input type="text" class="form-control"  name="beseda" autofocus>
            </div>
            <div class="form-group col-xs-2">
              Prevod<br>
              <input type="text" class="form-control"  name="prevod">
            </div>
            <div class="form-group col-xs-4">
              Opis<br>
              <input type="text" class="form-control"  name="opis" value=" ">
            </div>
            <div class="form-group col-xs-2">
              &nbsp;<br>
              <button type="submit" class="btn btn-default">
                Dodaj!
              </button>    
            </div>
          </div>
        </form>
  </div>
  <div class="col-md-1"></div>
</div>

<center>
<table class="table-striped" width="60%">  
  <tr>
    </tr>
  {% for beseda in besede %}
    <form action="{% url 'besede:vpisB'%}" method="POST" class="form-inline">
      {% csrf_token %}
         <input type="hidden" name="akcija" value="DEL">
         <input type="hidden" name="sID"    value="{{ sID }}">        
         <input type="hidden" name="bID"    value="{{ beseda.id }}">   
         <input type="hidden" name="beseda" value=".">   
         <input type="hidden" name="prevod" value=".">   
         <input type="hidden" name="opis"   value=".">   
       <tr>
        <td><div class="row">
            <div class="form-group col-xs-3">
              {{ beseda.beseda }}
            </div>
            <div class="form-group col-xs-3">
              {{ beseda.prevod }}              
            </div>
            <div class="form-group col-xs-6">
              {{ beseda.opis }}
            </div>
         </td>
       <td>
        <td valign=right>
        <button type="submit" class="btn-xs btn-blond btn-default">
          <span class="glyphicon glyphicon glyphicon-remove-sign" aria-hidden="true"></span></button>    
      </td>            
      </tr>
    </form>
  {%endfor %}
  </table> 
  </center>
  
</div>
{% endblock %}

besede/templates/vpisN.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<div class="ozadje">
  <center>
	  <h1 class="bottom-ena"><br>Izberi ali dodaj področje</h1>
<table>
	<tr>
		<form action="{% url 'besede:vpisN'%}" method="POST" class="form-inline">
	      {% csrf_token %}
	      <input type="hidden" name="akcija" value="ADD">
        <input type="hidden" name="nID"    value="0">
          <td><input  type="text" class="form-control"  name="nivo" autofocus>
          <td><button type="submit" class="btn btn-default">
            Dodaj področje
          </button>    
        </form>
    </tr> 
    <tr><td>&nbsp;</td></tr>
   {% for nivo in nivoji %}
	<form action="{% url 'besede:vpisN'%}" method="POST" class="form-inline">
	 {% csrf_token %}
	   <input type="hidden" name="akcija"  value="DEL">
     <input type="hidden" name="nID"     value="{{ nivo.id }}">        
     <input type="hidden" name="nivo"    value="{{ nivo }}">        
     <tr><td>
          <a href="{% url 'besede:vpisS'%}?nID={{ nivo.id }}"> {{ nivo }}</a>
         </td>
     	 <td><button type="submit" class="btn-xs btn-blond btn-default"
                   onclick="return confirm('Če pobrišeš področje, se bodo pobrisali vsi njegovi sklopi in besede.\n\n\nRes želiš pobrisati področje <{{ nivo }}>?');"
            >
          <span class="glyphicon glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
          </button>    
      </td></tr>
  </form>
   {%endfor %}
  </table> 
&nbsp;<br>
 </center>  
</div>
{% endblock %}

besede/templates/vpisS.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block body_block %}

<script >

</script>

<div class="ozadje">
  <center>
	<h1 class="bottom-ena top-ema">&nbsp;<br>{{ imeNivoja }}</h1>

<table>
  <tr>
    <form action="{% url 'besede:vpisS'%}" method="POST" class="form-inline">
        {% csrf_token %}
        <input type="hidden" name="akcija"    value="ADD">
        <input type="hidden" name="nID"       value="{{ nID }}">
        <input type="hidden" name="sID"       value="0">
          <td><input type="text" class="form-control"  name="sklop" autofocus>
          <td><button type="submit" class="btn btn-default">
            Dodaj sklop        
          </button>    
        </form>
    </tr> 
    <tr><td>&nbsp;</td></tr>
  {% for sklop in sklopi %}
    <form action="{% url 'besede:vpisS'%}" method="POST" class="form-inline">
      {% csrf_token %}
         <input type="hidden" name="akcija" value="DEL">
         <input type="hidden" name="nID"    value="{{ nID }}">        
         <input type="hidden" name="sID"    value="{{ sklop.id }}">   
         <input type="hidden" name="sklop"  value="{{ sklop }}">   
     <tr><td>
          <a href="{% url 'besede:vpisB'%}?sID={{ sklop.id }}"> {{ sklop }}</a>
         </td>
       <td><button type="submit" class="btn-xs btn-default btn-blond"
                   onclick="return confirm('Če pobrišeš sklop, se bodo pobrisale vse njegove besede.\n\n\nRes želiš pobrisati sklop <{{ sklop }}>?');"

           >
            <span class="glyphicon glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
          </button>    
      </td></tr>
  </form>
   {%endfor %}
  </table> 
  &nbsp;<br>  
</center>
</div>
{% endblock %}